# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba204a3e0ff21303be3bcdfc09e92345e018ec7449dddc793ca9e3200fbbbd39b18a5a7dc32e259042d0a1bd8040c02635f26849eedc1f40d45be37c5fa43cc8

test:
  secret_key_base: 911a333997af0b1088c895e199c47913668d070af459ec595d520c387bb556a1e8ff4c111c768263bca2826d0be65de4c887c69511bdcb9991dafb4e0349ca73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
